from backend.llm.gemini_client import GeminiClient


class ExecutiveAgent:

    """
    Executive Decision-Making Agent

    Responsibilities:
    - Summarize overall business performance
    - Highlight opportunities and risks
    - Recommend budget reallocations
    - Generate executive-level actions
    """

    def __init__(self):

        self.llm = GeminiClient()

    def analyze(
            self,
            trend_insights,
            budget_insights,
            visibility_insights,
            experimentation_insights=None
    ):

        prompt = f"""
You are the Vice President of Paid Search Analytics at American Express.

Your responsibility is to provide an executive business review for senior leadership.

Below are insights generated by specialized analytics teams.

==================================================
TREND ANALYST INSIGHTS
==================================================

{trend_insights}


==================================================
BUDGET OPTIMIZATION INSIGHTS
==================================================

{budget_insights}


==================================================
AI SEARCH VISIBILITY INSIGHTS
==================================================

{visibility_insights}


==================================================
EXPERIMENTATION INSIGHTS
==================================================

{experimentation_insights}


Using the information above, prepare an executive report.

Structure your response exactly as follows:

# Executive Summary

Provide a concise overview of overall performance.

# Key Business Drivers

Identify major growth drivers.

# Growth Opportunities

Highlight opportunities for customer acquisition.

# Risks and Challenges

Identify major risks affecting performance.

# Budget Recommendations

Recommend where investments should increase or decrease.

# AI Search Recommendations

Recommend actions to improve AI-powered search visibility.

# Experimentation Roadmap

Suggest future experiments.

# Expected Business Impact

Estimate expected impact on:
- Revenue
- Conversions
- Acquisition efficiency
- ROAS

# Top 5 Executive Actions

Provide the five highest-priority actions for leadership.
"""

        response = self.llm.generate(
            prompt
        )

        return response