from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak
)

from reportlab.lib.styles import (
    getSampleStyleSheet,
    ParagraphStyle
)

from reportlab.lib.enums import (
    TA_CENTER
)

from reportlab.lib.units import inch
from reportlab.lib.colors import navy, grey


class ReportGenerator:

    def create_report(
            self,
            text,
            filename
    ):

        doc = SimpleDocTemplate(
            filename,
            rightMargin=50,
            leftMargin=50,
            topMargin=50,
            bottomMargin=50
        )

        styles = getSampleStyleSheet()

        # ==========================================
        # CUSTOM STYLES
        # ==========================================

        title_style = ParagraphStyle(
            "TitleStyle",
            parent=styles["Title"],
            fontSize=22,
            leading=28,
            alignment=TA_CENTER,
            textColor=navy,
            spaceAfter=25
        )

        heading_style = ParagraphStyle(
            "HeadingStyle",
            parent=styles["Heading2"],
            fontSize=15,
            leading=20,
            textColor=navy,
            spaceBefore=15,
            spaceAfter=10
        )

        body_style = ParagraphStyle(
            "BodyStyle",
            parent=styles["BodyText"],
            fontSize=11,
            leading=18,
            spaceAfter=10
        )

        footer_style = ParagraphStyle(
            "FooterStyle",
            parent=styles["BodyText"],
            alignment=TA_CENTER,
            textColor=grey
        )

        story = []

        # ==========================================
        # COVER TITLE
        # ==========================================

        story.append(
            Paragraph(
                "Executive Search Intelligence Report",
                title_style
            )
        )

        story.append(
            Spacer(1, 0.3 * inch)
        )

        # ==========================================
        # FORMAT GEMINI RESPONSE
        # ==========================================

        lines = text.split("\n")

        for line in lines:

            line = line.strip()

            if not line:
                continue

            # Convert markdown headings
            if line.startswith("#"):

                heading = line.replace("#", "").strip()

                story.append(
                    Spacer(1, 0.15 * inch)
                )

                story.append(
                    Paragraph(
                        heading,
                        heading_style
                    )
                )

            # Bullet points
            elif line.startswith("-"):

                bullet = f"• {line[1:].strip()}"

                story.append(
                    Paragraph(
                        bullet,
                        body_style
                    )
                )

            else:

                story.append(
                    Paragraph(
                        line,
                        body_style
                    )
                )

        # ==========================================
        # FOOTER
        # ==========================================

        story.append(
            Spacer(1, 0.5 * inch)
        )

        story.append(
            Paragraph(
                "Generated by AI Search Intelligence Copilot",
                footer_style
            )
        )

        doc.build(story)

        return filename